### ISSUE TITLE
2 packages with same name in commit fd5f9bd096c6ecf7091275e52c0593e49c78453a of local/zsh-compatibility-simulation

### ISSUE THREAD

**Issue by duchainer** [WalkingMachine/sara_install#67]
rosdep install --from-paths src --ignore-src -r -y

ERROR: Rosdep experienced an error: Multiple packages found with the same name "roboticsgroup_gazebo_plugins":
- robotiq_140_gripper/robotiq_85_simulation/roboticsgroup_gazebo_plugins
- sara_description/third_party/roboticsgroup_gazebo_plugins
Please go to the rosdep page [1] and file a bug report with the stack trace below.
[1] : http://www.ros.org/wiki/rosdep

rosdep version: 0.18.0

Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 144, in rosdep_main
    exit_code = _rosdep_main(args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 428, in _rosdep_main
    return _package_args_handler(command, parser, options, args)
  File "/usr/lib/python2.7/dist-packages/rosdep2/main.py", line 483, in _package_args_handler
    pkgs = find_catkin_packages_in(path, options.verbose)
  File "/usr/lib/python2.7/dist-packages/rosdep2/catkin_packages.py", line 33, in find_catkin_packages_in
    packages = find_packages(path)
  File "/usr/lib/python2.7/dist-packages/catkin_pkg/packages.py", line 98, in find_packages
    raise RuntimeError('\n'.join(duplicates))
RuntimeError: Multiple packages found with the same name "roboticsgroup_gazebo_plugins":
- robotiq_140_gripper/robotiq_85_simulation/roboticsgroup_gazebo_plugins
- sara_description/third_party/roboticsgroup_gazebo_plugins

**Comment by Philippe117** [comment]
C'est quelle branche?
